### ISSUE TITLE
ERROR: Editor of class com.intellij.openapi.editor.impl.EditorImpl hasn't been released

### ISSUE THREAD

**Issue by yilongli** [orfjackal/idea-sbt-plugin#110]
I get this error consistently upon exit:
```
[  51660]  ERROR - api.util.objectTree.ObjectNode - Editor of class com.intellij.openapi.editor.impl.EditorImpl hasn't been released: 
--------------Creation trace: 
java.lang.Throwable
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:148)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:192)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createViewer(EditorFactoryImpl.java:173)
	at com.intellij.execution.impl.ConsoleViewUtil.setupConsoleEditor(ConsoleViewUtil.java:63)
	at com.intellij.execution.impl.ConsoleViewImpl.doCreateConsoleEditor(ConsoleViewImpl.java:958)
	at com.intellij.execution.impl.ConsoleViewImpl$15.compute(ConsoleViewImpl.java:901)
	at com.intellij.execution.impl.ConsoleViewImpl$15.compute(ConsoleViewImpl.java:898)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.execution.impl.ConsoleViewImpl.createConsoleEditor(ConsoleViewImpl.java:898)
	at com.intellij.execution.impl.ConsoleViewImpl.initConsoleEditor(ConsoleViewImpl.java:520)
	at com.intellij.execution.impl.ConsoleViewImpl.getComponent(ConsoleViewImpl.java:499)
	at net.orfjackal.sbt.plugin.SbtConsole.attachToToolWindow(SbtConsole.java:133)
	at net.orfjackal.sbt.plugin.SbtConsole.ensureAttachedToToolWindow(SbtConsole.java:122)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent.registerToolWindow(SbtRunnerComponent.java:112)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent.access$400(SbtRunnerComponent.java:35)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent$2.run(SbtRunnerComponent.java:91)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:339)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.java:331)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:191)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$8$2.run(ProjectManagerImpl.java:496)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
--------------Kill trace: 
java.lang.Throwable
	at com.intellij.openapi.util.TraceableDisposable.kill(TraceableDisposable.java:41)
	at com.intellij.openapi.editor.impl.EditorImpl.release(EditorImpl.java:815)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:211)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.validateEditorsAreReleased(EditorFactoryImpl.java:99)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$1$1.dispose(EditorFactoryImpl.java:66)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:47)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:132)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:146)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:122)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:146)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:132)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:108)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:104)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$14.run(ProjectManagerImpl.java:855)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:841)
	at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:302)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:299)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:780)
	at com.intellij.openapi.application.impl.ApplicationImpl.access$700(ApplicationImpl.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl$11.run(ApplicationImpl.java:756)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:762)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:711)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:706)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$4$1.run(IdeFrameImpl.java:253)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
-------------Own trace:
com.intellij.openapi.util.TraceableDisposable$DisposalException: Editor of class com.intellij.openapi.editor.impl.EditorImpl hasn't been released:
	at com.intellij.openapi.util.TraceableDisposable.throwDisposalError(TraceableDisposable.java:46)
	at com.intellij.openapi.editor.impl.EditorImpl.throwDisposalError(EditorImpl.java:807)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.throwNotReleasedError(EditorFactoryImpl.java:108)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.validateEditorsAreReleased(EditorFactoryImpl.java:96)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$1$1.dispose(EditorFactoryImpl.java:66)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:47)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:132)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:146)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:122)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:146)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:132)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:108)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:104)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$14.run(ProjectManagerImpl.java:855)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:841)
	at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:302)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:299)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:780)
	at com.intellij.openapi.application.impl.ApplicationImpl.access$700(ApplicationImpl.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl$11.run(ApplicationImpl.java:756)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:762)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:711)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:706)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$4$1.run(IdeFrameImpl.java:253)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[  51664]  ERROR - api.util.objectTree.ObjectNode - IntelliJ IDEA 14.1.4  Build #IC-141.1532.4 
[  51665]  ERROR - api.util.objectTree.ObjectNode - JDK: 1.8.0_45 
[  51665]  ERROR - api.util.objectTree.ObjectNode - VM: Java HotSpot(TM) 64-Bit Server VM 
[  51665]  ERROR - api.util.objectTree.ObjectNode - Vendor: Oracle Corporation 
[  51665]  ERROR - api.util.objectTree.ObjectNode - OS: Linux 
[  51665]  ERROR - api.util.objectTree.ObjectNode - Last Action:  
[  51665]  ERROR - api.util.objectTree.ObjectNode - Current Command: Exit 
[  52124]   WARN - api.vfs.impl.local.FileWatcher - Watcher terminated with exit code 0
```

**Comment by akozlova** [comment]
A lot of in our tracker, please investigate
Editor of class com.intellij.openapi.editor.impl.EditorImpl hasn't been released:

--------------Creation trace: 
java.lang.Throwable
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:144)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:193)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createViewer(EditorFactoryImpl.java:174)
	at com.intellij.execution.impl.ConsoleViewUtil.setupConsoleEditor(ConsoleViewUtil.java:63)
	at com.intellij.execution.impl.ConsoleViewImpl.doCreateConsoleEditor(ConsoleViewImpl.java:1001)
	at com.intellij.execution.impl.ConsoleViewImpl$16.compute(ConsoleViewImpl.java:943)
	at com.intellij.execution.impl.ConsoleViewImpl$16.compute(ConsoleViewImpl.java:940)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
	at com.intellij.execution.impl.ConsoleViewImpl.createConsoleEditor(ConsoleViewImpl.java:940)
	at com.intellij.execution.impl.ConsoleViewImpl.initConsoleEditor(ConsoleViewImpl.java:526)
	at com.intellij.execution.impl.ConsoleViewImpl.getComponent(ConsoleViewImpl.java:505)
	at net.orfjackal.sbt.plugin.SbtConsole.attachToToolWindow(SbtConsole.java:133)
	at net.orfjackal.sbt.plugin.SbtConsole.ensureAttachedToToolWindow(SbtConsole.java:122)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent.registerToolWindow(SbtRunnerComponent.java:112)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent.access$400(SbtRunnerComponent.java:35)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent$2.run(SbtRunnerComponent.java:91)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:342)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.java:334)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:182)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$5$2.run(ProjectManagerImpl.java:390)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:948)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:210)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:642)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:354)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:183)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:369)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:465)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:183)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:46)
	at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:61)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$2.onClick(RecentProjectPanel.java:124)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6543)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$MyList.processMouseEvent(RecentProjectPanel.java:350)
	at java.awt.Component.processEvent(Component.java:6308)
	at java.awt.Container.processEvent(Container.java:2235)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2293)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
	at java.awt.Container.dispatchEventImpl(Container.java:2279)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
--------------Kill trace: 
java.lang.Throwable
	at com.intellij.openapi.util.TraceableDisposable.kill(TraceableDisposable.java:41)
	at com.intellij.openapi.editor.impl.EditorImpl.release(EditorImpl.java:866)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:212)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.validateEditorsAreReleased(EditorFactoryImpl.java:100)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$1$1.dispose(EditorFactoryImpl.java:67)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:46)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:43)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:132)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:146)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:122)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:146)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:132)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:107)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:103)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$10.run(ProjectManagerImpl.java:635)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:627)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:654)
	at com.intellij.ide.impl.ProjectUtil.closeAndDispose(ProjectUtil.java:87)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$5$1.run(IdeFrameImpl.java:267)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
-------------Own trace:
com.intellij.openapi.util.TraceableDisposable$DisposalException: Editor of class com.intellij.openapi.editor.impl.EditorImpl hasn't been released:
	at com.intellij.openapi.util.TraceableDisposable.throwDisposalError(TraceableDisposable.java:52)
	at com.intellij.openapi.editor.impl.EditorImpl.throwDisposalError(EditorImpl.java:858)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.throwNotReleasedError(EditorFactoryImpl.java:109)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.validateEditorsAreReleased(EditorFactoryImpl.java:97)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$1$1.dispose(EditorFactoryImpl.java:67)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:46)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:43)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:132)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:146)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:122)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:146)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:106)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:132)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:107)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:103)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$10.run(ProjectManagerImpl.java:635)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:627)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:654)
	at com.intellij.ide.impl.ProjectUtil.closeAndDispose(ProjectUtil.java:87)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$5$1.run(IdeFrameImpl.java:267)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jameskoch** [comment]
ivyidea project reports the same issue:

https://github.com/guymahieu/ivyidea/issues/122

Here's their fix:

https://github.com/guymahieu/ivyidea/commit/203eeff90b9c56e8124f7bfb62acc9e8f21f5ce7
