### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by ice1000** [orfjackal/idea-sbt-plugin#124]
Plugin throws an exception when I was checking out some branches.

```
java.lang.IllegalArgumentException: Area already instantiated for: ProjectDefault (Template) Project
	at com.intellij.openapi.extensions.Extensions.instantiateArea(Extensions.java:129)
	at com.intellij.openapi.project.impl.ProjectImpl.bootstrapPicoContainer(ProjectImpl.java:146)
	at com.intellij.openapi.project.impl.DefaultProject$1$1.init(DefaultProject.java:67)
	at com.intellij.openapi.project.impl.DefaultProject$1.init(DefaultProject.java:96)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:33)
	at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:123)
	at com.intellij.openapi.project.impl.DefaultProject.getComponent(DefaultProject.java:213)
	at com.intellij.openapi.wm.ToolWindowManager.getInstance(ToolWindowManager.java:26)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent.unregisterToolWindow(SbtRunnerComponent.java:117)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent.disposeComponent(SbtRunnerComponent.java:98)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.disposeComponents(ComponentManagerImpl.java:185)
	at com.intellij.openapi.project.impl.ProjectImpl.dispose(ProjectImpl.java:323)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:135)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:104)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:214)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:104)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:137)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:133)
	at com.intellij.util.Timed.dispose(Timed.java:41)
	at com.intellij.util.TimedReference.dispose(TimedReference.java:22)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.lambda$null$0(DefaultProjectTimed.java:47)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:369)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:125)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:264)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1045)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:263)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:320)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:322)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:263)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:245)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:127)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:369)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:361)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.lambda$dispose$1(DefaultProjectTimed.java:47)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:97)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:415)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:749)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by xylo** [comment]
I got the same exception with IDEA 2019.2 EAP.

BTW: The issue title is irritating because it does not match the exception at all.

**Comment by xylo** [comment]
The exception occurs immediately after opening a project.

**Comment by steven-lai** [comment]
Confirmed on:

SBT plugin v1.8.0

```
IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 22, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: debugger.watches.in.variables=false, debugger.valueTooltipAutoShowOnSelection=true
Non-Bundled Plugins: CopyFQNPlugin, GrepConsole, SBT, io.protostuff.protostuff-jetbrains-plugin, org.intellij.scala, izhangzhihao.rainbow.brackets, org.jetbrains.plugins.hocon, BashSupport, PythonCore
```

**Comment by ice1000** [comment]
Seems that this project is dead
