### ISSUE TITLE
Error with Font increased anormally my cpu temperature

### ISSUE THREAD

**Issue by jvican** [orfjackal/idea-sbt-plugin#97]
Hi everybody!
I got an error with SBT in Intellij. When I start it, it increases my cpu to max level and CPU temperature shoot up, then it appears a window error which warns me that there's a bug with your plugin. It asks me to contact with Esko Kuontola who said he wasn't in charge of the plugin anymore. That's why I put it here. The error message I get is:

_"sun.font.CompositeFont cannot be cast to sun.font.PhysicalFont"_

My editor font is _"Inconsolata"_.

Stack trace:
sun.font.CompositeFont cannot be cast to sun.font.PhysicalFont: sun.font.CompositeFont cannot be cast to sun.font.PhysicalFont
java.lang.ClassCastException: sun.font.CompositeFont cannot be cast to sun.font.PhysicalFont
    at sun.font.CompositeFont.doDeferredInitialisation(CompositeFont.java:266)
    at sun.font.CompositeFont.getSlotFont(CompositeFont.java:334)
    at sun.font.CompositeStrike.getStrikeForSlot(CompositeStrike.java:77)
    at sun.font.CompositeStrike.getFontMetrics(CompositeStrike.java:93)
    at sun.font.FontDesignMetrics.initMatrixAndMetrics(FontDesignMetrics.java:359)
    at sun.font.FontDesignMetrics.<init>(FontDesignMetrics.java:350)
    at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:302)
    at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1027)
    at javax.swing.JComponent.getFontMetrics(JComponent.java:1624)
    at com.intellij.openapi.editor.impl.EditorImpl.getLineHeight(EditorImpl.java:3497)
    at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.getFoldingAnchorWidth(EditorGutterComponentImpl.java:974)
    at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.calcIconAreaWidth(EditorGutterComponentImpl.java:645)
    at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.updateSize(EditorGutterComponentImpl.java:548)
    at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.revalidateMarkup(EditorGutterComponentImpl.java:542)
    at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.reinitSettings(EditorGutterComponentImpl.java:193)
    at com.intellij.openapi.editor.impl.EditorImpl.reinitSettings(EditorImpl.java:719)
    at com.intellij.openapi.editor.impl.EditorImpl.setColorsScheme(EditorImpl.java:5069)
    at com.intellij.execution.impl.ConsoleViewUtil$1.run(ConsoleViewUtil.java:87)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:900)
    at com.intellij.execution.impl.ConsoleViewUtil.setupConsoleEditor(ConsoleViewUtil.java:66)
    at com.intellij.execution.console.LanguageConsoleImpl.setupEditorDefault(LanguageConsoleImpl.java:304)
    at com.intellij.execution.console.LanguageConsoleImpl.setupComponents(LanguageConsoleImpl.java:222)
    at com.intellij.execution.console.LanguageConsoleImpl.initComponents(LanguageConsoleImpl.java:173)
    at net.orfjackal.sbt.plugin.SbtConsole.createLanguageConsole(SbtConsole.java:102)
    at net.orfjackal.sbt.plugin.SbtConsole.createConsoleView(SbtConsole.java:81)
    at net.orfjackal.sbt.plugin.SbtConsole.<init>(SbtConsole.java:72)
    at net.orfjackal.sbt.plugin.SbtRunnerComponent.createConsole(SbtRunnerComponent.java:103)
    at net.orfjackal.sbt.plugin.SbtRunnerComponent.access$300(SbtRunnerComponent.java:35)
    at net.orfjackal.sbt.plugin.SbtRunnerComponent$2.run(SbtRunnerComponent.java:90)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.java:259)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:176)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$5$2.run(ProjectManagerImpl.java:446)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by renodesper** [comment]
I have the same issue, haven't found anything useful about what's going on.

**Comment by jvican** [comment]
I hardly remember but I solve it changing the font of the console in Intellij settings or tinkering with some options in the console settings.

**Comment by renodesper** [comment]
I see, I don't know what option that should be changed, but it was solved after I install some basic fonts (dejavu?). As far as I can remember I already install it the first time I install my operating system. I guess I accidentally remove it (can't remember).

By the way, thank you for the information.
